FROM python:3.9-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY ./activities_not_found.html .
COPY ./bad_request.html .
COPY ./csrf_token.html .
COPY ./edamam_api.py .
COPY ./forbidden.html .
COPY ./form.html .
COPY ./ninja_api.py .
COPY ./results.html .

EXPOSE 80
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
